import {
  Activity as ActivityIcon,
  BookOpen,
  Boxes,
  ChartSpline,
  Cog,
  Compass,
  GitBranch,
  Globe,
  HeartPulse,
  Network,
  Orbit,
  PawPrint,
  ShoppingBag,
  Skull,
  History,
  Target,
  Trophy,
  Users,
} from "lucide-react";

const spriteAssets = {
  creatures: {
    snail: new URL("./assets/sprites/creatures/snail.png", import.meta.url).href,
    fox: new URL("./assets/sprites/creatures/fox.png", import.meta.url).href,
    axolotl: new URL("./assets/sprites/creatures/axolotl.png", import.meta.url).href,
    cat: new URL("./assets/sprites/creatures/cat.png", import.meta.url).href,
    owl: new URL("./assets/sprites/creatures/owl.png", import.meta.url).href,
    mushroom: new URL("./assets/sprites/creatures/mushroom.png", import.meta.url).href,
    robot: new URL("./assets/sprites/creatures/robot.png", import.meta.url).href,
    dragon: new URL("./assets/sprites/creatures/dragon.png", import.meta.url).href,
    ghost: new URL("./assets/sprites/creatures/ghost.png", import.meta.url).href,
    bat: new URL("./assets/sprites/creatures/bat.png", import.meta.url).href,
    turtle: new URL("./assets/sprites/creatures/turtle.png", import.meta.url).href,
    penguin: new URL("./assets/sprites/creatures/penguin.png", import.meta.url).href,
    bee: new URL("./assets/sprites/creatures/bee.png", import.meta.url).href,
    slime: new URL("./assets/sprites/creatures/slime.png", import.meta.url).href,
    rabbit: new URL("./assets/sprites/creatures/rabbit.png", import.meta.url).href,
    frog: new URL("./assets/sprites/creatures/frog.png", import.meta.url).href,
    redPanda: new URL("./assets/sprites/creatures/red-panda.png", import.meta.url).href,
    capybara: new URL("./assets/sprites/creatures/capybara.png", import.meta.url).href,
    chameleon: new URL("./assets/sprites/creatures/chameleon.png", import.meta.url).href,
    crab: new URL("./assets/sprites/creatures/crab.png", import.meta.url).href,
    octopus: new URL("./assets/sprites/creatures/octopus.png", import.meta.url).href,
    moth: new URL("./assets/sprites/creatures/moth.png", import.meta.url).href,
    deer: new URL("./assets/sprites/creatures/deer.png", import.meta.url).href,
    gecko: new URL("./assets/sprites/creatures/gecko.png", import.meta.url).href,
  },
  emotes: {
    heart: new URL("./assets/sprites/emotes/heart.png", import.meta.url).href,
    smile: new URL("./assets/sprites/emotes/smile.png", import.meta.url).href,
    laugh: new URL("./assets/sprites/emotes/laugh.png", import.meta.url).href,
    sleep: new URL("./assets/sprites/emotes/sleep.png", import.meta.url).href,
    surprise: new URL("./assets/sprites/emotes/surprise.png", import.meta.url).href,
    wave: new URL("./assets/sprites/emotes/wave.png", import.meta.url).href,
    cry: new URL("./assets/sprites/emotes/cry.png", import.meta.url).href,
    starry: new URL("./assets/sprites/emotes/starry.png", import.meta.url).href,
    snailFace: new URL("./assets/sprites/emotes/snail-face.png", import.meta.url).href,
    foxFace: new URL("./assets/sprites/emotes/fox-face.png", import.meta.url).href,
    catFace: new URL("./assets/sprites/emotes/cat-face.png", import.meta.url).href,
    batFace: new URL("./assets/sprites/emotes/bat-face.png", import.meta.url).href,
    thumbsUp: new URL("./assets/sprites/emotes/thumbs-up.png", import.meta.url).href,
    musicNote: new URL("./assets/sprites/emotes/music-note.png", import.meta.url).href,
    sparkStar: new URL("./assets/sprites/emotes/spark-star.png", import.meta.url).href,
    networkBubble: new URL("./assets/sprites/emotes/network-bubble.png", import.meta.url).href,
    moonBubble: new URL("./assets/sprites/emotes/moon-bubble.png", import.meta.url).href,
    bandwidthBubble: new URL("./assets/sprites/emotes/bandwidth-bubble.png", import.meta.url).href,
  },
  skills: {
    radar: new URL("./assets/sprites/skills/radar.png", import.meta.url).href,
    tunnelSpiral: new URL("./assets/sprites/skills/tunnel-spiral.png", import.meta.url).href,
    shield: new URL("./assets/sprites/skills/shield.png", import.meta.url).href,
    paw: new URL("./assets/sprites/skills/paw.png", import.meta.url).href,
    networkNode: new URL("./assets/sprites/skills/network-node.png", import.meta.url).href,
    lightning: new URL("./assets/sprites/skills/lightning.png", import.meta.url).href,
    burst: new URL("./assets/sprites/skills/burst.png", import.meta.url).href,
    orbit: new URL("./assets/sprites/skills/orbit.png", import.meta.url).href,
    emerald: new URL("./assets/sprites/skills/emerald.png", import.meta.url).href,
    diamond: new URL("./assets/sprites/skills/diamond.png", import.meta.url).href,
    pinkGem: new URL("./assets/sprites/skills/pink-gem.png", import.meta.url).href,
    goldBadge: new URL("./assets/sprites/skills/gold-badge.png", import.meta.url).href,
    cyanStar: new URL("./assets/sprites/skills/cyan-star.png", import.meta.url).href,
    leafSignal: new URL("./assets/sprites/skills/leaf-signal.png", import.meta.url).href,
    coinRing: new URL("./assets/sprites/skills/coin-ring.png", import.meta.url).href,
    alertBloom: new URL("./assets/sprites/skills/alert-bloom.png", import.meta.url).href,
    heartShield: new URL("./assets/sprites/skills/heart-shield.png", import.meta.url).href,
    goldStar: new URL("./assets/sprites/skills/gold-star.png", import.meta.url).href,
  },
  items: {
    wizardHat: new URL("./assets/sprites/items/wizard-hat.png", import.meta.url).href,
    cap: new URL("./assets/sprites/items/cap.png", import.meta.url).href,
    glasses: new URL("./assets/sprites/items/glasses.png", import.meta.url).href,
    scarf: new URL("./assets/sprites/items/scarf.png", import.meta.url).href,
    crown: new URL("./assets/sprites/items/crown.png", import.meta.url).href,
    cyanCrystal: new URL("./assets/sprites/items/cyan-crystal.png", import.meta.url).href,
    blueCrystal: new URL("./assets/sprites/items/blue-crystal.png", import.meta.url).href,
    purpleOrb: new URL("./assets/sprites/items/purple-orb.png", import.meta.url).href,
    sprout: new URL("./assets/sprites/items/sprout.png", import.meta.url).href,
    ufo: new URL("./assets/sprites/items/ufo.png", import.meta.url).href,
    sleepZ: new URL("./assets/sprites/items/sleep-z.png", import.meta.url).href,
    mushroom: new URL("./assets/sprites/items/mushroom.png", import.meta.url).href,
    lensGem: new URL("./assets/sprites/items/lens-gem.png", import.meta.url).href,
    portalOrb: new URL("./assets/sprites/items/portal-orb.png", import.meta.url).href,
    relayAntenna: new URL("./assets/sprites/items/relay-antenna.png", import.meta.url).href,
    goldenBell: new URL("./assets/sprites/items/golden-bell.png", import.meta.url).href,
  },
} as const;

export const navItems = [
  { label: "Observatory", icon: Orbit },
  { label: "Guide", icon: BookOpen },
  { label: "Traffic", icon: ChartSpline },
  { label: "Peers", icon: Users },
  { label: "Tunnels", icon: Network },
  { label: "Health", icon: HeartPulse },
  { label: "Creature", icon: PawPrint },
  { label: "Collection", icon: Boxes },
  { label: "Quests", icon: Target },
  { label: "Shop", icon: ShoppingBag },
  { label: "Skills", icon: GitBranch },
  { label: "Achievements", icon: Trophy },
  { label: "Expeditions", icon: Compass },
  { label: "Eepsites", icon: Globe },
  { label: "Bosses", icon: Skull },
  { label: "Activity", icon: ActivityIcon },
  { label: "Timeline", icon: History },
  { label: "Settings", icon: Cog },
];

export const nodes = [
  { x: 50, y: 18, name: "Owl", role: "NetDB Scout", sprite: spriteAssets.creatures.owl, color: "#a7b4ff", mood: "Hey there!", size: 98 },
  { x: 76, y: 20, name: "Fox", role: "Outbound Pool", sprite: spriteAssets.creatures.fox, color: "#ff8b3d", mood: "Fresh tunnel", size: 98 },
  { x: 20, y: 44, name: "Dragon", role: "Transit Relay", sprite: spriteAssets.creatures.dragon, color: "#62e4c2", mood: "Sharing bandwidth!", size: 100 },
  { x: 52, y: 52, name: "Your Pet", role: "Local Router", sprite: spriteAssets.creatures.snail, color: "#ffe7a6", mood: "Let's keep the network alive!", size: 118 },
  { x: 84, y: 52, name: "Cat", role: "Peer Cluster", sprite: spriteAssets.creatures.cat, color: "#9d9cb8", mood: "Quiet relay", size: 92 },
  { x: 12, y: 76, name: "Mushroom", role: "Tunnel Builder", sprite: spriteAssets.creatures.mushroom, color: "#b280ff", mood: "Building tunnels!", size: 94 },
  { x: 35, y: 79, name: "Axolotl", role: "Inbound Pool", sprite: spriteAssets.creatures.axolotl, color: "#ff7bd5", mood: "Nice to meet you!", size: 94 },
  { x: 64, y: 82, name: "Slime", role: "Bandwidth Relay", sprite: spriteAssets.creatures.slime, color: "#55c8ff", mood: "Passing by", size: 84 },
];

export const creatureSprites = [
  { name: "Snail", src: spriteAssets.creatures.snail },
  { name: "Fox", src: spriteAssets.creatures.fox },
  { name: "Axolotl", src: spriteAssets.creatures.axolotl },
  { name: "Cat", src: spriteAssets.creatures.cat },
  { name: "Owl", src: spriteAssets.creatures.owl },
  { name: "Mushroom", src: spriteAssets.creatures.mushroom },
  { name: "Robot", src: spriteAssets.creatures.robot },
  { name: "Dragon", src: spriteAssets.creatures.dragon },
  { name: "Ghost", src: spriteAssets.creatures.ghost },
  { name: "Bat", src: spriteAssets.creatures.bat },
  { name: "Turtle", src: spriteAssets.creatures.turtle },
  { name: "Penguin", src: spriteAssets.creatures.penguin },
  { name: "Bee", src: spriteAssets.creatures.bee },
  { name: "Slime", src: spriteAssets.creatures.slime },
  { name: "Rabbit", src: spriteAssets.creatures.rabbit },
  { name: "Frog", src: spriteAssets.creatures.frog },
  { name: "Red Panda", src: spriteAssets.creatures.redPanda },
  { name: "Capybara", src: spriteAssets.creatures.capybara },
  { name: "Chameleon", src: spriteAssets.creatures.chameleon },
  { name: "Crab", src: spriteAssets.creatures.crab },
  { name: "Octopus", src: spriteAssets.creatures.octopus },
  { name: "Moth", src: spriteAssets.creatures.moth },
  { name: "Deer", src: spriteAssets.creatures.deer },
  { name: "Gecko", src: spriteAssets.creatures.gecko },
];

export const emoteSprites = [
  { name: "Heart", src: spriteAssets.emotes.heart },
  { name: "Smile", src: spriteAssets.emotes.smile },
  { name: "Laugh", src: spriteAssets.emotes.laugh },
  { name: "Sleep", src: spriteAssets.emotes.sleep },
  { name: "Surprise", src: spriteAssets.emotes.surprise },
  { name: "Wave", src: spriteAssets.emotes.wave },
  { name: "Cry", src: spriteAssets.emotes.cry },
  { name: "Starry", src: spriteAssets.emotes.starry },
  { name: "Snail", src: spriteAssets.emotes.snailFace },
  { name: "Fox", src: spriteAssets.emotes.foxFace },
  { name: "Cat", src: spriteAssets.emotes.catFace },
  { name: "Bat", src: spriteAssets.emotes.batFace },
  { name: "Thumb", src: spriteAssets.emotes.thumbsUp },
  { name: "Music", src: spriteAssets.emotes.musicNote },
  { name: "Spark", src: spriteAssets.emotes.sparkStar },
  { name: "Network", src: spriteAssets.emotes.networkBubble },
  { name: "Moon", src: spriteAssets.emotes.moonBubble },
  { name: "Boost", src: spriteAssets.emotes.bandwidthBubble },
];

export const skillSprites = [
  { name: "Radar", src: spriteAssets.skills.radar },
  { name: "Tunnel", src: spriteAssets.skills.tunnelSpiral },
  { name: "Shield", src: spriteAssets.skills.shield },
  { name: "Paw", src: spriteAssets.skills.paw },
  { name: "Network", src: spriteAssets.skills.networkNode },
  { name: "Lightning", src: spriteAssets.skills.lightning },
  { name: "Burst", src: spriteAssets.skills.burst },
  { name: "Orbit", src: spriteAssets.skills.orbit },
  { name: "Emerald", src: spriteAssets.skills.emerald },
  { name: "Diamond", src: spriteAssets.skills.diamond },
  { name: "Pink Gem", src: spriteAssets.skills.pinkGem },
  { name: "Badge", src: spriteAssets.skills.goldBadge },
  { name: "Star", src: spriteAssets.skills.cyanStar },
  { name: "Leaf", src: spriteAssets.skills.leafSignal },
  { name: "Coin", src: spriteAssets.skills.coinRing },
  { name: "Alert", src: spriteAssets.skills.alertBloom },
  { name: "Heart", src: spriteAssets.skills.heartShield },
  { name: "Gold Star", src: spriteAssets.skills.goldStar },
];

export const itemSprites = [
  { name: "Hat", src: spriteAssets.items.wizardHat },
  { name: "Cap", src: spriteAssets.items.cap },
  { name: "Specs", src: spriteAssets.items.glasses },
  { name: "Scarf", src: spriteAssets.items.scarf },
  { name: "Crown", src: spriteAssets.items.crown },
  { name: "Shard", src: spriteAssets.items.cyanCrystal },
  { name: "Crystal", src: spriteAssets.items.blueCrystal },
  { name: "Orb", src: spriteAssets.items.purpleOrb },
  { name: "Sprout", src: spriteAssets.items.sprout },
  { name: "UFO", src: spriteAssets.items.ufo },
  { name: "Sleep", src: spriteAssets.items.sleepZ },
  { name: "Mush", src: spriteAssets.items.mushroom },
  { name: "Lens", src: spriteAssets.items.lensGem },
  { name: "Portal", src: spriteAssets.items.portalOrb },
  { name: "Relay", src: spriteAssets.items.relayAntenna },
  { name: "Bell", src: spriteAssets.items.goldenBell },
];
